<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="assets/css/dealer.css" />
</head>
<body>
    <div class="container">
        <header>
    <nav>
        <ul>
            <li><a href="index.php?goto=voiture">Ajouter Voiture</a></li>
            <li><a href="index.php?goto=admin&target=inscription">Ajouter utilisateur</a></li>
            <li><a href="index.php?goto=admin&target=store">Ajout de lien</a></li>
            <li><a href="index.php?goto=admin&target=consulter">Consulter les clients ayant réservé</a></li>
            <li><a href="index.php?goto=publier">Publier un nouvel article</a></li>
            <li><a href="index.php?goto=inscription&target=listeClient">Liste des utilisateurs</a></li>
        </ul>
    </nav>
    <button><a href="index.php?goto=connexion&target=Destroy_session">Déconnexion</a></button>
        </header>
        
        <main>
       <?php include $template ?>
        </main>
    

    </body>
    </div>
</html>