<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="assets/css/dealer.css" />
</head>
<body>
    <div class="container">
        <header class="dashboardbane tac">
            <h1>EESPACE DE GESTION ADMIN</h1>
        </header>
    
        <main>
       <?php include $template ?>
        </main>
    
        <footer class="bg_footer">
            <hr>
            <p>Corporight 2023 tout droit réservé.. développé par PilotAmir</p>
        </footer>
    </body>
    </div>
</html>