<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="assets/css/dealer.css" />
</head>
<body class="ea">
    <div class="container">
        <header>
    <nav>

    <!-- <ul>
            <?php if(isset($_SESSION['links'])): ?>
                    <?php foreach($_SESSION['links'] as $link): ?>
                    <li><a href="index.php?goto=<?=$link['nav_goto']?>&target=<?=$link['nav_target']?>"><?=$link['links_name']?></a></li>
                    <?php endforeach ?>
            <?php endif ?>   
            </ul> -->

        <ul>
            <li><a href="index.php?goto=voiture">Ajouter Voiture</a></li>
            <li><a href="index.php?goto=admin&target=consulter">Gestion des utilisateurs</a></li>
            
            <li><a href="index.php?goto=reservation&target=liste_reservation">Consulter les clients ayant réservé</a></li>
            <li><a href="index.php?goto=admin&target=article">Publier un nouvel article</a></li>
            <li><a href="index.php?goto=connexion&target=Destroy_session">Déconnexion</a></li>
        </ul>
    </nav>
        </header>
        
        <main>
       <?php include $template ?>
        </main>
    

    </body>
    </div>
</html>