<div class="tac">
    <h2>A propos de nous</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, nemo debitis maiores ab magnam consequuntur nostrum mollitia ad suscipit incidunt explicabo, est excepturi accusamus voluptatem deleniti animi dolorem enim consequatur.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque soluta enim iusto doloremque nemo consequuntur, ea praesentium tempore ex quo sunt sapiente ipsam error animi odio? Labore, et architecto. Nobis.</p>
    <video controls poster="./assets/img/latest-news-bg.png">
        <source src = "./assets/medias/cooking.mp4" type="video/mp4">
    </video>

    <h2>Nos Voitures de reves</h2>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus suscipit fugit repellendus officia, odio iure? Itaque vel quo neque dolorem quidem beatae modi obcaecati eum sapiente saepe. Deserunt, sapiente laboriosam.</p>

</div> 

<div class = "galery tac">
    <figure>
        <img src="./assets/img/bmw_x6.png" alt="bmw_x6">
        <figcaption>bmw_x6</figcaption>
    </figure>

    <figure>
        <img src="./assets/img/feature-car4.png" alt="feature-car4">
        <figcaption>feature-car4</figcaption>
    </figure>

    <figure>
        <img src="./assets/img/feature-car5.png" alt="feature-car5">
        <figcaption>feature-car5</figcaption>
    </figure>

    <figure>
        <img src="./assets/img/feature-car2.png" alt="feature-car2">
        <figcaption>feature-car2</figcaption>
    </figure>



</div>
