<div class="tac">
    <h2>A propos de nous</h2>
    <p>Envie de voiture de Luxe a moindre cout, nous vous offrons la possiblité d'en avoir chez nous le plus vite possible et surtout a un cout qui défie toute concurrence</p>

    <p>N'attend pas de te faire prier et inscris toi pour réserver ta voiture de reve chez nous</p>
   

    <div class="about">
            
            <?php if (isset($article)) : ?>
                
                
                <?php foreach ($article as $key => $values) : ?>
                    
                    <div class = "about_up">

                        <h2><?=$values["titre"]?></h2>
                        
                        <img src="<?=$values["image_article"]?>" alt ="image_article">
                        
                    </div>
                    <div class="commentaire"><p ><?=$values["commentaire"]?> </p> 
                    </div>

                   
                <?php endforeach ?> 
            <?php endif ?>

    </div>

</div> 


