<div class="banner">

  <div class="titre">
  <h1>EXPLORE YOUR DREAM CAR</h1>
  
  <img src="./assets/img/car-border1.png" alt="car-border1">
  <p>Avec nous, votre rêve devient réalité. Votre voiture de rêve est a votre porté juste en quelques click</p>
  <a href="#">DISCOVER MORE</a>
  </div>
</div>

  <h2 class="tac">BIENVENUE CHEZ LUXURY CAR DEALER</h2>
  <p class="tac"> <img src="./assets/img/car-border.png" alt="car-border"> </p>

  <section class="margin_bottom">
    <article>
      <div>
        <p class="tac"><a href=""><svg class="icon_main" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6">
                    <path fill-rule="evenodd" d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.007 5.404.433c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.433 2.082-5.006z" clip-rule="evenodd" />
                  </svg></a>
        </p>
                  
        <h2 class="tac">HIGHLY TRAINED-STAFF</h2>
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Error dignissimos corporis unde deserunt labore quidem exercitationem accusamus accusantium perspiciatis reiciendis itaque, dolores numquam totam eius mollitia quia iste sit eveniet?
        </p>
      </div>    
        </article>



        <article>
          <div>
            <p class="tac"><a href=""><svg class="icon_main" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6">
                    <path fill-rule="evenodd" d="M12 2.25c-5.385 0-9.75 4.365-9.75 9.75s4.365 9.75 9.75 9.75 9.75-4.365 9.75-9.75S17.385 2.25 12 2.25zM12.75 6a.75.75 0 00-1.5 0v6c0 .414.336.75.75.75h4.5a.75.75 0 000-1.5h-3.75V6z" clip-rule="evenodd" />
                  </svg></a>
            </p>
                  
            <h2 class="tac">FAST & EFFECTIVE SERVICES</h2>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Cupiditate temporibus similique id quos commodi pariatur asperiores modi aspernatur obcaecati, aliquam ullam corporis ab vero itaque quia doloremque ex, facilis qui!
            </p>
          </div>
           
        </article>


        <article>
            <div>
              <p class="tac"><a href=""><svg class="icon_main" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6">
                    <path fill-rule="evenodd" d="M1.5 4.5a3 3 0 013-3h1.372c.86 0 1.61.586 1.819 1.42l1.105 4.423a1.875 1.875 0 01-.694 1.955l-1.293.97c-.135.101-.164.249-.126.352a11.285 11.285 0 006.697 6.697c.103.038.25.009.352-.126l.97-1.293a1.875 1.875 0 011.955-.694l4.423 1.105c.834.209 1.42.959 1.42 1.82V19.5a3 3 0 01-3 3h-2.25C8.552 22.5 1.5 15.448 1.5 6.75V4.5z" clip-rule="evenodd" />
                  </svg></a>
              </p>
                  
              <h2 class="tac">SUPPORT 24/7</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem repellat quos quas nostrum molestias asperiores quam corporis minus odio? Quae expedita deleniti quidem natus totam est tempore nostrum et ullam.
              </p>    
        </article>
    </section>

   

   
   
</div>
