
<div>

    <form action="" method="post">
        <fieldset>
            <legend>
                Ajout de lien
            </legend>
        
        <label for="links_name">links_name:</label>
        <input type="text" name="links_name" id="links_name"><br><br>

        <label for="nav_goto">nav_goto:</label>
        <input type="text" name="nav_goto" id="nav_goto"><br><br>

        <label for="nav_target">nav_target:</label>
        <input type="text" name="nav_target" id="nav_target"><br><br>

        <button type="submit">Envoyer</button><br><br>
        </fieldset>
    </form>

</div>