
    <div class="bane">
        <div class = "titre">
        <h1 >START THE AVENTURE WITH US</h1>
        <img src="./assets/img/car-border1.png" alt="car-border1">
        <p>Avec nous, votre rêve devient réalité. Votre voiture de rêve est a votre porté juste en quelques click</p>
        </div>
        
    </div>
    <h2 class="tac">NOS VOITURES DE LUXES</h2>
    <p class="tac">CHOISIS PARMIS LES 4 MARQUES LES PLUS LUXUEUSES DU MONDE</p>
    <div class="filter">
    <button><a href="index.php?goto=catalogue&target=index">ALL</a></button>
    <button><a href="index.php?goto=catalogue&target=bmw">BMW</a></button>
    <button><a href="index.php?goto=catalogue&target=audi">AUDI</a></button>
    <button><a href="index.php?goto=catalogue&target=mercedes">MERCEDES</a></button>
    <button><a href="index.php?goto=catalogue&target=lamborghini">LAMBORGHINI</a></button>
    
    </div>


    <div class="choice">
            
            <?php if (isset($liste_voiture)) : ?>
                
                <?php foreach ($liste_voiture as $key => $values) : ?>
                    <div>
                        <img src="<?=$values["images_voitures"]?>" alt ="voiture_de_luxe">
                    </div>
                   
                <?php endforeach ?> 
            <?php endif ?>   
    </div>


    
    