
<div class="main-form">
    <form action="" method="post" class="connect">
        
            
            <div>
                <input type="text" name="id_user" id="id_user">
                <i class="fa-sharp fa-solid fa-user"></i>
                <label for="id_user">Identifiant </label>
            </div>

            <div>
                <input type="password" name="mdp" id="mdp">
                <i class="fa-solid fa-house-lock"></i>
                <label for="mdp">password</label>
            </div>

          <p> Vous n'avez pas encore de compte?  <a href="index.php?goto=inscription">Inscrivez-vous!</a></p>

            <button type="submit">Connexion</button>
        
    </form>
</div>