<form action="" method="post" class="connect">
        <fieldset>
            <legend>Connecte toi et réserve en 3 click!!</legend>
            <div>
            <label for="id_user">Identifiant :</label>
            <input type="text" name="id_user" id="id_user"><br><br>
            </div>

            <div>
            <label for="mdp">Mot de passe :</label>
            <input type="text" name="mdp" id="mdp"><br><br>
            </div>
            <a href="index.php?goto=inscription">Vous n'avez pas encore de compte? Inscrivez-vous!</a>

            <button type="submit">Connexion</button>
        </fieldset>
    </form>
