<h2 class="tac">Bienvenue sur l'espace Administrateur</h2>
<nav>
    <ul>
        <li><a href="index.php?goto=voiture">Ajouter Voiture</a></li>
        <li><a href="index.php?goto=inscription">Ajouter utilisateur</a></li>
        <li><a href="index.php?goto=admin&target=store">Ajout de lien</a></li>
        <li><a href="index.php?goto=consulter">Consulter les clients ayant réservé</a></li>
        <li><a href="index.php?goto=publier">Publier un nouvel article</a></li>
    </ul>
</nav>
<button><a href="index.php?goto=connexion&target=Destroy_session">Déconnexion</a></button>
