<div class="main-form"> 
         <form action="" method="post">
            <h2>Ajoute un membre <span>L</span>uxury <span>C</span>ar<span>_D<span>ealer</h2>

            <div>
                
                <input type="text" name="nom" id="nom" placeholder="Nom">
            </div>
                
            <div>
                
                <input type="text" name="prenom" id="prenom" placeholder="Prenom">
            </div>

            <div>
                
                <input type="email" name="email" id="email" placeholder="Email">
                
            </div>

            <div>
                
                <input type="text" name="tel" id="tel" placeholder = "Telephone">
            </div>

            <div>
                
                <input type="text" name="identifiant" id="identifiant" placeholder = "Identifiant">
            </div>

            <div>
                
                <input type="password" name="mdp" id="mdp" placeholder="Mot de passe">
            </div>

            <div>
                
                <input type="password" name="cmdp" id="cmdp" placeholder="Confirmation">
            </div>

                <button type = "submit" name = "envoyer" >Je m'inscris</button>
            </form>
        </div> 
<div>
        <?php if (isset($liste_client)) : ?>
            <table>
                <tr>
                    <th>N°</th>
                    <th>Nom</th>
                    <th>Prenom</th>
                    <th>Email</th>
                    <th>Tel</th>
                    <th>Login</th>
                    <th colspan="2">Action</th>

                </tr>
                <?php foreach ($liste_client as $key => $values) : ?>
                    <tr>
                        <td><?= $num++ ?></td>
                        <td><?= $values['nom'] ?></td>
                        <td><?= $values['prenom'] ?></td>
                        <td><?= $values['email'] ?></td>
                        <td><?= $values['tel'] ?></td>
                        <td><?= $values['identifiant'] ?></td>
                        <td><button style="background-color:gray; color:white;"><a href="index.php?goto=inscription&target=update<?= $values['Id'] ?>">Edit</a></button></td>
                        <td><button style="background-color:brown; color:white;"><a href="index.php?goto=inscription&target=destroy&id=<?= $values['client_id'] ?>">Delete</a></button></td>
                    </tr>
                <?php endforeach ?>
            </table>

        <?php endif ?>
        
    </div>