<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
        
         <div class="main-form"> 
         <form action="" method="post">
            <h2>Rejoins La Famille <span>L</span>uxury <span>C</span>ar<span>_D<span>ealer</h2>

            <div>
                
                <input type="text" name="nom" id="nom" placeholder="Nom">
            </div>
                
            <div>
                
                <input type="text" name="prenom" id="prenom" placeholder="Prenom">
            </div>

            <div>
                
                <input type="email" name="email" id="email" placeholder="Email">
                
            </div>

            <div>
                
                <input type="text" name="tel" id="tel" placeholder = "Telephone">
            </div>

            <div>
                
                <input type="text" name="identifiant" id="identifiant" placeholder = "Identifiant">
            </div>

            <div>
                
                <input type="password" name="mdp" id="mdp" placeholder="Mot de passe">
            </div>

            <div>
                
                <input type="password" name="cmdp" id="cmdp" placeholder="Confirmation">
            </div>

                <button type = "submit" name = "envoyer"  placeholder="">Je m'inscris</button>
            </form>
        </div> 

        
    

</body>
</html>