<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
        
         <div class="main-form"> 
         <form action="" method="post">

            <div>
                <label for="nom">Nom :</label>
                <input type="text" name="nom" id="nom">
            </div>
                
            <div>
                <label for="prenom">Prenom :</label>
                <input type="text" name="prenom" id="prenom">
            </div>

            <div>
                <label for="email">Email :</label>
                <input type="email" name="email" id="email">
            </div>

            <div>
                <label for="tel">Telephone :</label>
                <input type="text" name="tel" id="tel">
            </div>

            <div>
                <label for="identifiant">Identifiant :</label>
                <input type="text" name="identifiant" id="identifiant">
            </div>

            <div>
                <label for="mdp">Mot de Passe :</label>
                <input type="password" name="mdp" id="mdp">
            </div>

            <div>
                <label for="cmdp">Confirmation Mot de Passe :</label>
                <input type="password" name="cmdp" id="cmdp">
            </div>

                <button type = "submit" name = "envoyer" >Envoyer</button>
            </form>
        </div> 

        
    

</body>
</html>