<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="post">
        <fieldset>
            <legend>INSCRIS TOI ET RESERVE TA VOITURE NEGRO</legend>

            <label for="nom">Nom :</label>
            <input type="text" name="nom" id="nom"><br>

            <label for="prenom">Prenom :</label>
            <input type="text" name="prenom" id="prenom"><br>

            <label for="email">Email :</label>
            <input type="email" name="email" id="email"><br>

            <label for="tel">Telephone :</label>
            <input type="number" name="tel" id="tel"><br>

            <label for="identifiant">Identifiant</label>
            <input type="text" name="identifiant" id="identifiant"><br><br>

            <label for="mdp">Mot de Passe</label>
            <input type="password" name="mdp" id="mdp"><br><br>

            <label for="cmdp">Confirmation Mot de Passe</label>
            <input type="password" name="cmdp" id="cmdp">

            <button type = "submit" name = "envoyer" >Envoyer</button>

        </fieldset>
    </form>

    <div>
        <img src="./assets/img/brand3.png" alt="brand3">
    </div>

</body>
</html>