
<h3 class = 'tac' >Voici la liste des clients qui ont reserver</h3>
<div>

        <?php if (isset($liste_reservation)) : ?>
            
            <table>
                <tr>
                    <th>N°</th>
                    <th>Nom</th>
                    <th>Prenom</th>
                    <th>Num-Réservation</th>
                    <th>Num-voiture</th>
                    <th>Date-Reservation</th>
                    <th>Pack</th>
                    <th>Brand</th>
                    <th>Model</th>
                    <th>Couleur</th>
                    <th>Prix TTC</th>
                    
                </tr>
                <?php foreach ($liste_reservation as $key => $values) : ?>
                    <tr>
                        <td><?= $num++ ?></td>
                        <td><?= $values['nom'] ?></td>
                        <td><?= $values['prenom'] ?></td>
                        <td><?= $values['reservation_id'] ?></td>
                        <td><?= $values['voiture_reserv'] ?></td>
                        <td><?= $values['date_de_reservation'] ?></td>
                        <td><?= $values['pack_reserver'] ?></td>
                        <td><?= $values['voiture_brand'] ?></td>
                        <td><?= $values['voiture_model'] ?></td>
                        <td><?= $values['voiture_color'] ?></td>
                        <td><?= $values['voiture_price'] ?></td>
                        
                    </tr>
                <?php endforeach ?>
            </table>

        <?php endif ?>
        
    </div>