
    <div class="bane">
        <h2 class="tac">LE MONDE AUTREMENT</h2>
    </div>
    <h2 class="tac">NOS VOITURES DE LUXES</h2>
    <p class="tac">CHOISIS PARMIS LES 4 MARQUES LES PLUS LUXUEUSES DU MONDE</p>
    <div class="filter">
    <button >ALL</button>
    <button >BMW</button>
    <button >AUDI</button>
    <button >MERCEDES</button>
    <button>LAMBORGHINI</button>
    </div>


    <div class="choice">
        <figure>
            <img src="./assets/img/feature-car1.png" alt="feature-car1">
            <figcaption>feature-car1</figcaption>
        </figure>

        <figure>
            <img src="./assets/img/feature-car4.png" alt="feature-car4">
            <figcaption>feature-car4</figcaption>
        </figure>

        <figure>
            <img src="./assets/img/feature-car2.png" alt="feature-car2">
            <figcaption>feature-car2</figcaption>
        </figure>

        <figure>
            <img src="./assets/img/feature-car6.png" alt="feature-car6">
            <figcaption>feature-car6</figcaption>
        </figure>

        <figure>
        <img src="./assets/img/feature-car5.png" alt="feature-car6">
        <figcaption>feature-car6</figcaption>
    </figure>

    <figure>
        <img src="./assets/img/bmw_x6.png" alt="bmw_x6">
        <figcaption>bmw_x6</figcaption>
    </figure>

    </div>
