<div class="main-form"> 
  <form action="" method="post" enctype="multipart/form-data">

        <div>
            
            <input type="radio" name="voiture_brand" id="voiture_brand" value="bmw">

            <label for="voiture_brand">BMW</label><br>

            <input type="radio" name="voiture_brand" id="voiture_brand" value="audi">

            <label for="voiture_brand">AUDI</label><br>

            <input type="radio" name="voiture_brand" id="voiture_brand" value="mercedes">

            <label for="voiture_brand">MERCEDES</label><br>

            <input type="radio" name="voiture_brand" id="voiture_brand" value="lamborghini">

            <label for="voiture_brand">LAMBORGHINI</label><br>

        </div>

        <div>
            <label for="voiture_model">Voiture model</label>
            <input type="text" name="voiture_model" id="voiture_model" placeholder = "voituremodel" value='<?=(isset($b)) ? $b['voiture_model'] : '' ?>' >
        </div>
        <div>
            <label for="voiture_color">Voiture color</label>
            <input type="text" name="voiture_color" id="voiture_color" value='<?=(isset($b)) ? $b['voiture_color'] : '' ?>' >
        </div>
        <div>
            <label for="voiture_price">Voiture price</label>
            <input type="text" name="voiture_price" id="voiture_price" value='<?=(isset($b)) ? $b['voiture_price'] : '' ?>' >
        </div>
        <input type="hidden" name="MAX_FILE_SIZE" value="3000000">
            <div >
            <input type="file" name="img" class="form-control">
            </div>
        
        <button type="text" name="send" >Envoyer</button>

    </form>
</div> 
<div>
<?php if(isset($liste_voiture)):?>
    <table>
        <tr>
            <th>N°</th>
            <th>Brand</th>
            <th>Model</th>
            <th>Couleur</th>
            <th>Prix</th>
            <th>Image</th>
        </tr>
    <?php foreach($liste_voiture as $key=>$values): ?>
        <tr>
            <td><?=$num++?></td>
            <td><?=$values['voiture_brand']?></td>
            <td><?=$values['voiture_model']?></td>
            <td><?=$values['voiture_color']?></td>
            <td><?=$values['voiture_price']?></td>
            <td><?=$values['images_voitures']?></td>
            <td><button style="background-color:gray; color:white;"><a href="index.php?goto=voiture&target=updateVoit&id=<?= $values['voiture_id'] ?>">Edit</a></button></td>
                        <td><button style="background-color:brown; color:white;"><a href="index.php?goto=voiture&target=destroy&id=<?= $values['voiture_id'] ?>">Delete</a></button></td>
        </tr>
        <?php endforeach ?>
    </table>
    <?php endif ?>
    </div>
